%Subpunctul a);
z=[0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0] % Creez un vector cu lungimea 21;
n=0:20 % Creez un vector cu lungimea 21, continand numere de la 0 la 20;
m=-5:15 %creez un vector cu lungimea 21, continand numere de la -5 la 15;
subplot(2,1,1) % Imi va afisa o minifereastra;
figure(1); % Creeaza o figura;
stem(n,z) % Afiseaza z in functie de n;
subplot(2,1,2) %Creez alta minifereastra;
stem(m,z) %Afiseaza z in functie de m;
%Subpunctul b);
n=0:20 % Creez un vector cu lungimea 21, continand numere de la 0 la 20;
t=abs(10-n) % Vectorul t ia valorile din "n-10" in modul;
figure(2); %Creeaza o figura;
stem(n,t) % Afiseaza t in functie de n;
%Subpunctul c);
n=-15:25 % Creez un vector cu lungimea 41, continand numere de la -15 la 25;
x1=sin(pi*n/17) % Calculez sin din paranteza;
figure(3); % Creeaza o figura;
stem(n,x1); % Afiseaza x1 in functie de n;
hold on % Retine graficul curent si adauga in aceeasi fereastra grafica urmatoarele reprezentari grafice;
n=0:50 % Creez un vector cu lungimea 51, continand numere de la 0 la 50;
x2=cos(pi*n/sqrt(23)) % Calculez cosinus din fractia din paranteza;
stem(n,x2); % Afiseaza x2 in functie de n;
figure(4);	% Creeaza o figura;	
subplot(2,1,1)	% Imi va afisa o minifereastra;	
n=-15:25	% Creez un vector cu lungimea 41, continand numere de la -15 la 25;	
x1=sin(pi*n/17)	% Calculez sin din paranteza;	
plot(n,x1)	% Grafic ce contine n si x1;	
subplot(2,1,2)	% Imi va afisa o minifereastra;		
n=0:50	% Creez un vector cu lungimea 51, continand numere de la 0 la 50;		
x2=cos(pi*n/sqrt(23))	% Calculez cosinus din fractia din paranteza;
plot(n,x2)	% Grafic ce contine n si x2;